### PR TITLE
Add natural tranformations to base

### PR DESCRIPTION
**Pull request by janstenpickle**

### CODE REVIEW

**Comment by catostrophe** [comment]
@janstenpickle Why did you add mapK/imapK only to 2 of them? Do you have any particular application? Could they be useful in Ask/Local?

**Comment by janstenpickle** [comment]
> @janstenpickle Why did you add mapK/imapK only to 2 of them? Do you have any particular application? Could they be useful in Ask/Local?

It's because the inhertance structure causes issues when adding these methods on the less powerful abstractions.

**Comment by catostrophe** [comment]
> > @janstenpickle Why did you add mapK/imapK only to 2 of them? Do you have any particular application? Could they be useful in Ask/Local?
> 
> It's because the inhertance structure causes issues when adding these methods on the less powerful abstractions.

Hmmm... I think I can do it. Let me try tonight.

**Comment by catostrophe** [comment]
I can't push to PR branches, so I created a separate PR #191

**Pull request merged**
